# AI Agent Configuration

# OpenAI Configuration
openai:
  api_key: "your-openai-api-key-here"
  model: "deepseek-chat"
  temperature: 0.7
  max_tokens: 2000

# Anthropic Configuration
anthropic:
  api_key: "your-anthropic-api-key-here"
  model: "claude-3-sonnet-20240229"
  temperature: 0.7
  max_tokens: 2000

# Agent Configuration
agent:
  max_iterations: 10
  timeout_seconds: 300
  enable_memory: true
  enable_reflection: true

# Tool Configuration
tools:
  enable_file_operations: true
  enable_web_search: false
  enable_calculator: true
  enable_code_execution: false

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/ai_agent.log"
  console_output: true

# Visualization Configuration
visualization:
  enable_cli_visualization: true
  enable_notebook_visualization: true
  max_trajectory_steps: 50